name: 'Nutrition Pit Blog '
favicon: null
layout_spectrum: 0.7549344694707543
typography_spectrum: 0.6007666373625398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7984300802927464
  lightness: 0.6082398311700672
  saturation: 0.6172033443581313
  rhythmicContrast: 0.333069741493091
purpose: []
